import type { Metadata } from "next";
import alipic from "../../public/alipic.png";
import Image from "next/image";

import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <div className="logo-container">
              <Image src={alipic} alt="CodeWithAli" className="logo" />
            </div>
            <div className="nav-links">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/courses">Courses</Link>
              <Link href="/#contact">Contact</Link>
              <Link href="/#reviews">Reviews</Link>
              <Link href="/#faq">FAQ</Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
